#! /bin/sh
### BEGIN INIT INFO
# Provides: forever node
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Node.js App Init Script
# Description: This file should be used to construct scripts to be
# placed in /etc/init.d.
### END INIT INFO
 
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
 
case "$1" in
start)
exec forever \
-l /home/cleric/app/forever/forever.log \
-o /home/cleric/app/forever/output.log \
-e /home/cleric/app/forever/errors.log \
--sourceDir=/home/cleric/app/server/ \
--workingDir=/home/cleric/app/server/ \
-p /home/cleric/.forever \
--append \
--verbose \
-m 5 \
start build/index.js
;;
stop)
exec forever --sourceDir=/home/cleric/app/server/ stop build/index.js
;;
*)
echo "Usage: /etc/init.d/limo {start|stop}"
exit 1
;;
esac
 
exit 0